name: Bump casks
description: Bump outdated casks

inputs:
  HOMEBREW_GITHUB_API_TOKEN:
    description: "Homebrew GitHub API Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Bump outdated casks
      env:
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.HOMEBREW_GITHUB_API_TOKEN }}
      shell: bash -ieo pipefail {0}
      # GitHub API 认证额度 5000 次/小时，据此串行执行（-j1）并留出间隔。
      run: |
        parallel -j1 --delay 1s --group --halt now,fail=1 \
          "./.github/actions/bump-casks/script.sh shanyouli/tap/{}" \
          ::: $(ls $(brew --repository shanyouli/tap)/Casks/*.rb | xargs -I {} basename {} .rb)
