name: Auto Merge Owner PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'shanyouli'  # 替换为仓库所有者的 GitHub 用户名
    steps:
      - uses: actions/checkout@v4
      - name: Set up GitHub CLI
        uses: ksivamuthu/actions-setup-gh-cli@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto merge pull request
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        # run: gh pr merge --auto --squash ${{github.event.pull_request.html_url}}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
