name: schedule

on:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [fix-*]
  schedule:
    # Every 24 hours
    - cron: "0 2 */3 * *"
    # Every day at 6am
    # - cron: "0 6 * * *"
  # allow run manually
  workflow_dispatch:

permissions: write-all

jobs:
  casks:
    name: Bump Casks in parallel
    if: github.repository == 'shanyouli/homebrew-tap'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Homebrew env
        uses: ./.github/actions/homebrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump casks
        uses: ./.github/actions/bump-casks
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

  check_formula:
    runs-on: ubuntu-latest
    outputs:
      dir_exists: ${{ steps.check_dir.outputs.exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if directory exists
        id: check_dir
        run: |
          if [ -d "./Formula" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  formulas:
    name: Bump Formulae in parallel
    needs: check_formula
    if: github.repository == 'shanyouli/homebrew-tap' && needs.check_formula.outputs.dir_exists == 'true'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Homebrew env
        uses: ./.github/actions/homebrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      # - name: Bump formulae
      #   uses: ./.github/actions/bump-formulas
      #   with:
      #     HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
